services:
  postgres:
    image: 'postgres:latest'
    environment:
      # - 'POSTGRES_DB=mydatabase'
      # - 'POSTGRES_PASSWORD=secret'
      # - 'POSTGRES_USER=myuser'
        - 'POSTGRES_DB=scentshelf'
        - 'POSTGRES_PASSWORD=benji'
        - 'POSTGRES_USER=benji'
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
